name: release


on: push


jobs:
    superlinter:
        name: lint code base
        run on: ubuntu-latest
        steps:
        - name: Checkout code
          user: actions/checkout@v2
          env: 
            DEFAULT_BRANCH: main
            GUTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    

